# Generated by Django 4.2.1 on 2023-08-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_categoriaprod_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriaprod',
            table=None,
        ),
    ]
