# Generated by Django 4.2.1 on 2023-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
